// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0rcdvpyFH83lPHhPQlvZILNWTsIkqhQY',
    appId: '1:300216488861:web:cc514027fed7fc4de0d574',
    messagingSenderId: '300216488861',
    projectId: 'practice001-7a937',
    authDomain: 'practice001-7a937.firebaseapp.com',
    storageBucket: 'practice001-7a937.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCYW6HW2e75mPtmsFSufsiQL4zawDOqw',
    appId: '1:300216488861:android:dd79a8138947c953e0d574',
    messagingSenderId: '300216488861',
    projectId: 'practice001-7a937',
    storageBucket: 'practice001-7a937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEeNmX8fLK4zOWZ0yS9ezejLI_SI8HYA',
    appId: '1:300216488861:ios:b277c50eb94459c2e0d574',
    messagingSenderId: '300216488861',
    projectId: 'practice001-7a937',
    storageBucket: 'practice001-7a937.appspot.com',
    iosBundleId: 'com.example.practice001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEeNmX8fLK4zOWZ0yS9ezejLI_SI8HYA',
    appId: '1:300216488861:ios:24a9bc9069e4281ee0d574',
    messagingSenderId: '300216488861',
    projectId: 'practice001-7a937',
    storageBucket: 'practice001-7a937.appspot.com',
    iosBundleId: 'com.example.practice001.RunnerTests',
  );
}
